deploy:
  stage: deploy
  script:
    - rm -rf node_modules/
    - rm -rf package-lock.json
    - echo "VITE_APP_API_URL=https://fruity-backend.techpss.com/api/" > .env
    - npm install 
    - npm run build
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY_GITLAB_RUNNER_DEMOS" >> ~/.ssh/id_dsa
    - chmod 600 ~/.ssh/id_dsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - ssh $DEMO_SERVER rm -rf $DIRECTORY_PATH/$DEV_APP_PATH/$DEV_APP_BUILD_PATH_OLD
    - ssh $DEMO_SERVER mv $DIRECTORY_PATH/$DEV_APP_PATH/$DEV_APP_BUILD_PATH $DIRECTORY_PATH/$DEV_APP_PATH/$DEV_APP_BUILD_PATH_OLD
    - rsync -rav --delete dist/ $DEMO_SERVER:$DIRECTORY_PATH/$DEV_APP_PATH/$DEV_APP_BUILD_PATH
  environment:
    name: dev
  only:
    - dev